---

- name: "Push bash include"
  ansible.builtin.template:
    dest: /usr/local/etc/bash.d/terraform.sh
    group: root
    mode: "0644"
    owner: root
    src: terraform.sh.j2
  become: true
  tags: [ct-terraform]

- name: "Download archive"
  ansible.builtin.get_url:
    dest: "{{ hashicorp_dir_staging }}"
    mode: "0644"
    timeout: "{{ hashicorp_internet_timeout }}"
    url: "{{ hashicorp_repo }}/terraform/{{ terraform_version }}/{{ terraform_target }}"
    validate_certs: false
  tags: [ct-terraform]

- name: "Expand archive"
  ansible.builtin.unarchive:
    copy: false
    dest: "{{ hashicorp_dir_bin }}"
    src: "{{ hashicorp_dir_staging }}/{{ terraform_target }}"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  tags: [ct-terraform]

# --------------------------------
...
